name: Spell Check .md
on: push

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: Spellcheck
    steps:
      - uses: actions/checkout@v3
      - uses: tbroadley/spellchecker-cli-action@v1
        with:
          files: "**/*.md"
          quiet: true
